version: "3"

volumes:
  dbbackups:
  postgis-data:
services:
  main:
    image: http_proxy
    expose:
      - ${HTTP_PORT}
    networks:
      - default
    depends_on:
      - bd
  bd:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=proxy
      - POSTGRES_DB=proxy
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
networks:
  default:
    driver: bridge
